# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------------------------------------
# 日志配置
# ----------------------------------------------------------------------------------------------------------------------
logging:
  file:
    name: "playground"
    path: "./_log"
