version: "3.9"

services:
  playground:
    image: "yingzhuo/playground:latest"
    container_name: "playground"
    hostname: "playground"
    restart: "always"
    ports:
      - "8080:8080"
    networks:
      - playground-cluster

networks:
  playground-cluster:
    driver: bridge