# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  config:
    import: "optional:classpath:conf/playground-dev.xml"
