# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: "playground"
  profiles:
    active:
      - dev
    include:
      - default
  config:
    import:
      - "optional:classpath:/config/playground.yml"
  aop:
    auto: true
  main:
    web-application-type: servlet
    banner-mode: log
    allow-bean-definition-overriding: true
    lazy-initialization: false
    log-startup-info: true
    sources:
      - "classpath*:spring/*.xml"
  banner:
    location: banner.txt
  jackson:
    locale: "zh_CN"
    time-zone: "Asia/Shanghai"
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    default-property-inclusion: always
    serialization:
      indent-output: true
      fail-on-self-references: true
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
      write-null-map-values: true
      write-empty-json-arrays: true
      write-single-elem-arrays-unwrapped: false
      write-enums-using-to-string: true
    deserialization:
      fail-on-unknown-properties: false
  lifecycle:
    timeout-per-shutdown-phase: "30s"
  jmx:
    enabled: false

server:
  port: 8080
  servlet:
    context-path: "/"
  error:
    path: "/error"
  compression:
    enabled: true
    min-response-size: 2KB
  shutdown: graceful

# ----------------------------------------------------------------------------------------------------------------------
# 日志配置
# ----------------------------------------------------------------------------------------------------------------------
logging:
  file:
    name: "playground-core"
    path: "/var/log/playground"

# ----------------------------------------------------------------------------------------------------------------------
# Actuator
# ----------------------------------------------------------------------------------------------------------------------
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include:
            - "ping"
            - "livenessStateProbeIndicator"
        readiness:
          include:
            - "ping"
            - "livenessStateProbeIndicator"
            - "readinessStateProbeIndicator"
  info:
    git:
      enabled: true
      mode: full
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
      path-mapping:
        shutdown: "_shutdown"
